service: lendingFront

frameworkVersion: '3'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
 wsgi:
   app: app.app

 pythonRequirements:
    pythonBin: python3
    
provider:
  name: aws
  runtime: python3.11
  region: us-east-2

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
